### ISSUE TITLE
class Project should provide getter for db connection instead of direct access

### ISSUE THREAD

**Issue by nanokatze** [nyxxxie/spade#10]

**Comment by nyxxxie** [comment]
Do you mean provide a method called get_db() or something that returns sqlite object?  If that, sure.

**Comment by nanokatze** [comment]
ya. call it Project.db() and store db connection in Project._db

**Comment by nyxxxie** [comment]
Yeah sounds good, I'll add that method into the project class.

**Comment by nyxxxie** [comment]
Added function in a4c002895a5d378e8f7ed5ffa5158f98e5497942, issue solved.
