### ISSUE TITLE
Create CONTRIBUTING.md document

### ISSUE THREAD

**Issue by nyxxxie** [nyxxxie/spade#13]
This document should outline what kinds of submissions are welcome, development practices and expectations, coding styles, etc.  Move any complex guides to their own files in docs folder (for example, the process of creating and running tests?)

**Comment by nanokatze** [comment]
Must follow teh [PEP 8](https://www.python.org/dev/peps/pep-0008/) and all new core features (must be kept as low as necessary) should have a set of unit tests for them

**Comment by fst3a** [comment]
The problem is plugin licensing, what does gpl3 say on this regard?

**Comment by nyxxxie** [comment]
merged 17b2cd1b4ae76155 into devel, closing
