### ISSUE TITLE
changes_comments should have compound foreign key (file_id, hash)

### ISSUE THREAD

**Issue by nanokatze** [nyxxxie/spade#23]
There can exist same change hash for two or more different files.  Example:

0. you open two files with exactly same content
1. their base changes are both 0
2. erase first 4 bytes in both
3. change hash is sha256(base + file_pos + change_type + data)
4. get collision

**Comment by nyxxxie** [comment]
@fst3a is this fixed with sqlalchemy changes in feature/implement_project?

**Comment by nanokatze** [comment]
@nyxxxie no.
