### ISSUE TITLE
Please review current DB schema draft and decide on a way for File and FileView to access "changes" and "files" tables in the database

### ISSUE THREAD

**Issue by nanokatze** [nyxxxie/spade#5]
Current DB schema [draft](https://github.com/fst3a/spade/commit/8a7744d7bcad30ab53d9cbfb475ce61d7d385e67) for "files" and "changes" might not have things you will agree on so please review it and express your opinion on it.  Other than that, at the moment we access sqlite connection using Project.db member variable, is this going to stay this way or will it be hidden behind some methods?

**Comment by nyxxxie** [comment]
@fst3a Made a few comments on your draft

**Comment by nanokatze** [comment]
Updated
